info_by_key = {
        'ABSOLUTE_TERRAIN_ADAPTION':["Terrain adaption is absolute (model_cutout.fx): Vertices are absolutely adapted to the exact terrain height. Note: Needs 'Adjust to terrain height' to be enabled.", "Terrain adaption is absolute (model_materials.fxh): Vertices are absolutely adapted to the exact terrain height. Note: Needs 'Adjust to terrain height' to be enabled."],
        'ADJUST_TO_TERRAIN_HEIGHT':['Adjust to terrain height (cloth.fx): Every vertex position is adjusted according to the terrain height', 'Adjust to terrain height (model_lowpoly.fx): Every vertex position is adjusted according to the terrain height', 'Adjust to terrain height (model_materials.fxh): Every vertex position is adjusted according to the terrain height'],
        'AdaptTerrainHeight':['Adjust to terrain height: Position is adjusted according to the terrain height, i.e. the object will be exactly as many units above ground as it currently is'],
        'ALPHA_BLEND_ENABLED':["Alpha Blending (model_materials.fxh): Enables alpha blending. The diffuse texture's alpha channel specifies the opacity per pixel (alpha ref is disabled in this case)."],
        'ARCTIC_SHADING_ENABLED':["Arctic Shading (decal_terrain.fx): Enables arctic shading parameters. Use this for decals that will be placed on terrain with arctic shading. Note that this most prominently affects gloss: Instead of a single gloss value, 'icyness' and 'snowness' are baked."],
        'ATMOSPHERE_REFLECTION_ENABLED':['Reflect Atmosphere (model_planet_water.fx): Enables reflection of the atmosphere'],
        'BlenderModelID':['Will be converted to ModelID (corresponding to the index of that model in the .cfg) when exporting the file. Make sure that the referenced model is part of the same MAIN_FILE!'],
        'BlenderParticleID':['Will be converted to ParticleID when exporting the file. Make sure that the referenced particle is part of the same MAIN_FILE!'],
        'cAdaptToTerrainNormal':['Adapt to Terrain Normal (prop_terrain.fx): Adapts to the terrain normal in the skirt area'],
        'cAdjustToTerrainHeight':['Adjust to terrain height (model_cutout.fx): Every vertex position is adjusted according to the terrain height'],
        'cAlignOnWater':['Water align: 0=OFF | 1=Y | 2=XYZ (prop_decal.fx): Aligns the vertices on the water triangles, 0=OFF, 1=Y only, 2=XYZ'],
        'cAlignToTerrainNormal':["Align to Terrain Normal (prop_plant.fx): Rotates the mesh's vertices to align to the terrain normal (for props that are flagged with 'Adapt Terrain Height')", "Align Vertices to Terrain Normal (prop_terrain.fx): Rotates the mesh's vertices to align to the terrain normal (for props that are flagged with 'Adapt Terrain Height')", 'Align to Terrain Normal (prop_terrain_object.fxh): Offsets the mesh along the terrain normal (instead of simply up/down). Especially on cliffs this makes a difference!'],
        'cAlphaPower':['Alpha Power (model_video.fx): Alpha Power'],
        'cAlphaRef':['Alpha Ref (cloth.fx): Which alpha results in discarding of pixels?', 'Alpha Ref (model_frame_cycle.fx): Which alpha results in discarding of pixels?', 'Alpha Ref (prop_decal_detail.fx): Which alpha results in discarding of pixels?', 'Alpha Ref (prop_plant.fx): Which alpha results in discarding of pixels?', 'Alpha Ref (prop_terrain_object.fxh): Which alpha results in discarding of pixels?'],
        'cBaseReflectivity':["Reflectivity (model_water.fx): The water surface's reflectivity. This controls the mix of reflection vs. refraction. Note that the shader also adds a simple Fresnel effect: At grazing angles the water surface is always 100% reflective."],
        'cBlendDuration':["Blend Duration (model_frame_cycle.fx): Duration of the blending animation when switching to the next frame (in seconds). Must be less than 'Frame Duration'!"],
        'cBoostTerrainTinting':['Boost Terrain Tinting (prop_plant.fx): Applies a contrast filter to the terrain tint color'],
        'cBrightness':['Brightness (model_video.fx): Brightness'],
        'cClothDiffuseTex':['Diffuse + Alpha Texture (cloth.fx): Diffuse Color'],
        'cClothDyeMask':["Dye Mask Texture (cloth.fx): A gray mask that specifies the model's areas where e.g. the player color is shown."],
        'cClothNormalTex':['Normal + Gloss Texture (cloth.fx): Normal XY and Glossiness in alpha'],
        'cClothRippleTex':['Ripple Texture (cloth.fx): The texture used for the wind ripple effect'],
        'cCloudAnimationSpeed':['Cloud Animation Speed (model_planet.fx): Cloud animation speed'],
        'cCloudHeightTex':['Height Texture (model_planet.fx): Cloud height texture with different heights for each channel (RGBA)'],
        'cCloudLightingDepth':['Cloud Lighting Depth (model_planet.fx): How deep (step-size) are clouds lighted'],
        'cCloudLightingFalloff':['Cloud Lighting Falloff (model_planet.fx): Falloff of the cloud translucency lighting, i.e. the density of clouds'],
        'cCloudLightingIntensity':['Cloud Lighting Intensity (model_planet.fx): Intensity of cloud lighting'],
        'cCloudLightingPuffynessFalloff':['Cloud Lighting Puffyness Falloff (model_planet.fx): How fast puffy clouds fall back to their texture details'],
        'cCloudMovementSpeed':['Cloud Movement Speed (model_planet.fx): Cloud movement speed'],
        'cCloudReflectParallax':['Cloud Reflection Parallax (model_planet_water.fx): Parallax offset used for the cloud reflections'],
        'cCloudsHeight':['Clouds Height (model_planet.fx): Clouds Height'],
        'cCloudSpeed':['Cloud Speed (model_planet_water.fx): Texture scroll speed for the reflected cloud texture'],
        'cCloudTexScale':['Cloud Scale (model_planet_water.fx): Scale of the clouds texture'],
        'cCloudTintColor':['Cloud Tint Color (model_planet.fx): Cloud tint color'],
        'cDepthBias':['Depth bias (prop_decal.fx): Depth bias used to eliminate z-fighting of polygons'],
        'cDiffuseColor':['Diffuse Color (cloth.fx): Diffuse Color', 'Diffuse Color (decal_terrain.fx): Diffuse Color', 'Diffuse Color (model_frame_cycle.fx): Diffuse Color', 'Diffuse Color (model_lowpoly.fx): Diffuse Color', 'Diffuse Color (model_planet_water.fx): Diffuse color', 'Diffuse Color (prop_decal.fx): Diffuse Color', 'Diffuse Color (prop_decal_detail.fx): Diffuse Color', 'Diffuse Color (prop_plant.fx): Diffuse Color', 'Diffuse Color (model_materials.fxh): Diffuse Color'],
        'cDiffuseOpacity':["Diffuse Opacity (decal_terrain.fx): Opacity of the diffuse texture. Lower this value to bake decal's normal map onto the terrain without modifying terrain's albedo."],
        'cDiffuseTex':['Diffuse Texture File (model_planet_water.fx): Diffuse texture'],
        'cDisplacementScale':['Displacement scale (model_materials.fxh): The maximum displacement distance (Positive and negative).'],
        'cDyeMask':["Dye Mask Texture (model_materials.fxh): A gray mask that specifies the model's areas where e.g. the player color is shown."],
        'cEmissiveColor':['Emissive Color (model_materials.fxh): Emitted Color'],
        'cEnvironmentBoundingBox':['Env Bounding Box (model_materials.fxh): Bounding box of the environment map'],
        'cFlowNormalIntensity':["Normal Intensity (model_water.fx): Controls the normal map's intensity."],
        'cFlowSpeed':["Flow Speed (model_water.fx): Controls the water flow speed, additional to the flow map's red/green channels."],
        'cFoamDistortIntensity':["Foam Distortion (model_planet_water.fx): Controls the intensity of the foam texture's distortion"],
        'cFoamDistortSpeed':["Foam Distortion Speed (model_planet_water.fx): Controls the speed of the foam texture's distortion"],
        'cFoamMaskTex':['Foam Mask File (model_planet_water.fx): Foam mask texture'],
        'cFoamTileTex':['Foam Tile Texture File (model_planet_water.fx): Foam tile texture'],
        'cFoamTiling':["Foam Tiling (model_planet_water.fx): Controls the foam tile texture's tiling"],
        'cFrameDuration':['Frame Duration (model_frame_cycle.fx): Number of seconds a frame is shown until it switches to the next frame'],
        'cGlassReflectivity':['Reflectivity (model_glass.fx): Base reflectivity when looking straight down perpendicularly on the glass surface (aka. fresnel F0 term)'],
        'cGlossiness':['Glossiness (prop_decal_detail.fx): ', 'Glossiness (prop_terrain_object.fxh): '],
        'cGlossinessFactor':['Gloss Factor (cloth.fx): Multiplies Glossiness from texture', "Gloss Factor (decal_terrain.fx): Glossiness factor. If a glossiness mask is specified (normal map's alpha channel), this slider modifies it. Otherwise this slider defines the decal's overall glossiness. NOTE: THIS SLIDER HAS NO EFFECT WHEN ICE/SNOW IS ENABLED!", "Glossiness (model_lowpoly.fx): The material's glossiness (0.0 = rough, 1.0 = smooth)", 'Gloss Factor (model_planet_water.fx): Multiplies Glossiness from texture', 'Gloss Factor (prop_decal.fx): Multiplies Glossiness from texture', 'Gloss Factor (model_materials.fxh): Multiplies Glossiness from texture'],
        'cGlow':['Glow (model_lowpoly.fx): Self-illumination'],
        'cHeightFactor':['Height Factor (decal_terrain.fx): If a height map is specified, this slider modifies it.'],
        'cHeightMap':['Height Texture (decal_terrain.fx): Height texture (for parallax mapping)', 'Height Map Texture (model_materials.fxh): A Height map which can contain fine surface details.'],
        'cHorizonColor':['Horizon Color (model_planet_water.fx): Atmosphere color at horizon (for sky reflection)'],
        'cIcyness':["Icyness (decal_terrain.fx): Defines how icy this material is (same as terrain materials' icyness, specified in spec texture's red channel)"],
        'cImpostorAtlas0':['Diffuse + Alpha Atlas (model_impostor.fx): Diffuse + Alpha Atlas Texture'],
        'cImpostorAtlas1':['Normal + Depth Atlas (model_impostor.fx): Normal + Depth Atlas Texture'],
        'CLOUDS_ENABLED':['Clouds Enabled (model_planet.fx): Enables the planet clouds', 'Cloud Texture (model_planet_water.fx): Enables the cloud texture for reflections'],
        'cMaxCloudLightingPuffyness':['Max Cloud Lighting Puffyness (model_planet.fx): Maximum puffyness (mipmap-level) of clouds'],
        'cMaxDisplacement':['Max Displacement (prop_decal_detail.fx): Must match value in decal material.'],
        'cMetallicLowPoly':['Metallicity (model_lowpoly.fx): Is this material a dielectric (0.0, like plastic, concrete, wood) or a metal (1.0). Affects reflection.'],
        'cModelDiffTex':['Diffuse + Alpha Texture (decal_terrain.fx): Diffuse Color and Alpha', 'Diffuse + Alpha Texture (model_frame_cycle.fx): Diffuse Color and Alpha', 'Diffuse + Alpha Texture (model_video.fx): Diffuse Color and Alpha', 'Diffuse + Alpha Texture (model_materials.fxh): Diffuse Color and Alpha. Alpha is used for alpha-ref (erasing pixels with low alpha), except for some other shaders. Here alpha is used to increase opacity (a=0 -> take opacity. a=1 -> opacity = 1)'],
        'cModelMetallicTex':["Metallic Texture (functions_pbr.fxh): Is this material a dielectric (0.0, like plastic, concrete, wood) or a metal (1.0). Affects reflection. Alpha channel specifies ambient occlusion (AO). Bonus: Colors in this texture tint the reflection (the metallicity is defined by the texture's luma in this case)."],
        'cModelNormalTex':['Normal + Gloss Texture (decal_terrain.fx): Normal XY and Glossiness in alpha', 'Normal + Glow + Gloss Texture (model_materials.fxh): Normal XY, Glow in B and Glossiness in alpha'],
        'cNightGlowIntensity':['Night-Glow Intensity (model_planet.fx): Intensity of the night-light glow'],
        'cNightGlowMap':['Night Glow Texture (model_materials.fxh): Additional glow map that is only applied during night. Only uses the R channel.'],
        'cNormalSkirtHeight':["Skirt Height (prop_terrain.fx): Size of the skirt area near the terrain ground where the object's normal is blended to the terrain normal and the grit is always applied independently of the object's normal. A value of 0.0 disables the skirt."],
        'cNormalTex':['Normal Texture File (model_planet_water.fx): Normal texture (RG channels contain the normal, alpha channel contains glossiness)'],
        'cNumFrames':['Number of Frames (model_frame_cycle.fx): Total number of frames in the texture'],
        'cOpacity':['Opacity (model_frame_cycle.fx): How opaque is the object', 'CAUTION (model_planet.fx): DO NOT TOUCH! Controls whether the whole planet is rendered in the opaque or transparent pass.', 'Opacity (model_planet_water.fx): How opaque is the object', 'Opacity (model_video.fx): How opaque is the object', 'Opacity (prop_decal.fx): How opaque is the object', 'Opacity (model_materials.fxh): How opaque is the object'],
        'Condition':['Conditions: Condition under which the transform is active, used for a variety of things like making particles visible when the building is working. My understanding is that this value is actually a bitset, f.e. 64 stands for 01000000 and 96 stands for 01100000 (not actually 8bit, but still). Hence a conditions entry of 96 is a superset of both 32 and 64. Which condition corresponds to working/idle differs from building to building, so use existing condition codes to see which one corresponds to which. I think the <Type> 2 Tracks in the Animation Sequences have something to do with that.'],
        'Conditions':['Conditions: Condition under which the transform is active, used for a variety of things like making particles visible when the building is working. My understanding is that this value is actually a bitset, f.e. 64 stands for 01000000 and 96 stands for 01100000 (not actually 8bit, but still). Hence a conditions entry of 96 is a superset of both 32 and 64. Which condition corresponds to working/idle differs from building to building, so use existing condition codes to see which one corresponds to which. I think the <Type> 2 Tracks in the Animation Sequences have something to do with that.'],
        'cParallaxScale':['Parallax/Self-Shadow Scale (model_materials.fxh): The scale for parallax mapping and self shadowing'],
        'cParallaxStrength':['Parallax Strength (model_planet.fx): Parallax strength'],
        'cPlanetCloudTex':['Cloud Texture File (model_planet_water.fx): Cloud texture for reflections'],
        'cPlanetDayDiffTex':['Diffuse Texture Day (model_planet.fx): Diffuse color on sun-lit side'],
        'cPlanetDistance':['Planet Distance (model_planet.fx): Planet distance'],
        'cPlanetHeight':['Height Texture (model_planet.fx): Planet height for self-shadowing (e.g. mountains)'],
        'cPlanetNightDiffTex':['Night-Glow Texture (model_planet.fx): Glow (RGB) for lights during night'],
        'cPlanetNormalGloss':['Normal + Gloss Texture (model_planet.fx): Planet normals (RGB) and gloss (A)'],
        'cPlanetTintColor':['Planet Tint Color (model_planet.fx): Planet tint color'],
        'cPropArcticSpecTex':["Prop Ice/Snow (prop_terrain.fx): (if 'Terrain Material' is NOT checked) A texture defining the 'icyness' (R channel) and 'snowness' (G channel) of the prop. This works similar to the specular textures for arctic terrain materials."],
        'cPropDiffuseTex':['Diffuse + Alpha (prop_decal.fx): Diffuse Color', 'Diffuse + Alpha (prop_decal_detail.fx): Diffuse Color', 'Diffuse (prop_terrain.fx): Diffuse Color', 'Diffuse + Alpha (prop_terrain_object.fxh): Diffuse Color'],
        'cPropNormalTex':['Normal + Glow + Gloss (prop_decal.fx): Normal XY and Glossiness in alpha', 'Normal (prop_terrain.fx): Normal XY'],
        'cPropTerrainArcticSpecTex':["Terrain Spec (Ice/Snow) (prop_terrain.fx): (if 'Terrain Material' is checked) The specular texture that belongs to the terrain diffuse and normal texture. This defines the icyness/snowness of the tiled terrain texture, same as it does on an arctic terrain."],
        'cPropTerrainDiffuseTex':['Terrain Diffuse (prop_terrain.fx): Terrain Diffuse Texture'],
        'cPropTerrainNormalTex':['Terrain Normal (prop_terrain.fx): Terrain Normal Texture'],
        'cPropTintIntensity':['Prop Tint Intensity (prop_plant.fx): Controls how strongly the prop tint map affects this prop'],
        'cPropTintTiling':['Prop Tint Tiling (prop_plant.fx): Tiling factor for prop tinting'],
        'cRimColor':['Rim color (cloth.fx): Color of the rim effect (faded-in when looking parallel to the surface for a silk-like effect)'],
        'cRimIntensity':["Rim Intensity (cloth.fx): Controls the rim effect's intensity (fade to rim color when looking parallel to the surface for a silk-like effect)"],
        'cRippleNormalIntensity':["Ripple Normal Intensity (cloth.fx): Controls the wind ripples' normal mapping intensity"],
        'cRippleSpeed':["Ripple Speed (cloth.fx): Controls the wind ripple texture's movement speed"],
        'cRippleTiling':["Ripple Tiling (cloth.fx): Controls the wind ripple texture's tiling size"],
        'cRooftopSnow':['Rooftop snow (functions_snow.fxh): Additional snow on rooftops'],
        'cSeparateAOTex':['Separate AO Texture (functions_pbr.fxh): A separate ambient occlusion texture. Metallicity texture must be enabled. NOTE: The mesh needs a second UV channel!'],
        'cShadowAlphaRef':['Shadow Alpha Ref (prop_plant.fx): Threshold for shadow-casting pixels'],
        'cShallowFade':['Shallow Fade (model_planet_water.fx): How much to fade on shallow water'],
        'cSmallWaveTexScale':["Ocean Water Tex Scale (model_water.fx): Controls the ocean wave texture's scaling."],
        'cSnowDensity':['Snow density (functions_snow.fxh): The snow density of the object'],
        'cSnowness':["Snowness (decal_terrain.fx): Defines how snowy this material is (same as terrain materials' snowness, specified in spec texture's green channel)"],
        'cSnowRoughness':['Snow roughness (functions_snow.fxh): Infulence the snow normals and lighting'],
        'cSnowScale':['Snow scale (functions_snow.fxh): Scale factor used to scale the snow texture'],
        'cSpecularColor':['Specular Color (cloth.fx): Specular Color', 'Specular Color (prop_decal.fx): Specular Color'],
        'cSubSurfaceDepth':['Ice Sub-Surface Depth (prop_terrain.fx): Depth of the ice sub-surface texture (should be the same value as specified for the arctic terrain material set)'],
        'cSubSurfaceDistortion':['Ice Sub-Surface Distortion (prop_terrain.fx): Distortion of the ice sub-surface texture (should be the same value as specified for the arctic terrain material set)'],
        'cSubSurfaceTex':['Ice Sub-Surface Texture (prop_terrain.fx): Ice Sub-Surface Texture (rendered below ice; should be the same texture as specified for the arctic terrain material set)'],
        'cSubSurfaceTiling':['Ice Sub-Surface Tiling (prop_terrain.fx): Tiling of the ice sub-surface texture (should be the same value as specified for the arctic terrain material set)'],
        'cSunSpecAzimuthAngle':["Spec Azimuth Angle (model_planet_water.fx): The sun direction's azimuth angle (for spec only)"],
        'cSunSpecPolarAngle':["Spec Polar Angle (model_planet_water.fx): The sun direction's polar angle (for spec only)"],
        'cTerrainTexRepetition':['Repetition (prop_terrain.fx): Size of the terrain textures'],
        'cTerrainTintIntensity':['Terrain Tinting Intensity (prop_plant.fx): Controls how much the terrain tinting acts on this prop', 'Terrain Tinting Intensity (prop_terrain_object.fxh): Controls how much the terrain tinting acts on this object'],
        'cTexCoordRatio':['TextureCoordinate Ratio (model_planet.fx): Texture-coordinate ratio'],
        'cTexCoordScale':['TextureCoordinate Scale (model_planet.fx): Texture-coordinate scale'],
        'cTexScrollSpeed':['Texture Scroll Speed (model_frame_cycle.fx): How fast does the texture scroll along the U or V axis (in UV pages per second) while a sequence is running', 'Texture Scroll Speed (model_materials.fxh): How fast does the texture scroll along the U axis (in UV pages per second) while a sequence is running'],
        'cUseLocalEnvironmentBox':['Use Local Environment Box (model_materials.fxh): Enables/disables the local environment box for cube mapping (Env Bounding Box). When enabled, the cube map can be positioned and sized by parameters. When disabled, the shader is effectively using standard cube mapping (i.e. sampling from an infinitely large cube).'],
        'cUseTerrainGrit':["Use Terrain Grit (prop_decal.fx): Applies terrain's grit texture onto this model, depending on its slope", "Use Terrain Grit (prop_terrain.fx): Applies terrain's grit texture onto this prop, depending on its slope", "Use Terrain Grit (functions_pbr.fxh): Applies terrain's grit texture onto this model, depending on its slope"],
        'cUseTerrainTinting':["Use Terrain Tinting (prop_decal.fx): Applies terrain's luma/chroma tinting to the model", "Use Terrain Tinting (prop_plant.fx): Applies terrain's luma/chroma tinting to the model", "Use Terrain Tinting (functions_pbr.fxh): Applies terrain's luma/chroma tinting to the model", "Use Terrain Tinting (prop_terrain_object.fxh): Applies terrain's luma/chroma tinting to the model"],
        'CUT_OUT_TERRAIN':['Cut out terrain (model_cutout.fx): Cut out the terrain surface', 'Cut out terrain (model_volume_cutout.fx): Cut out the terrain surface'],
        'CUT_OUT_WATER':['Cut out water (model_cutout.fx): Cut out the ocean water surface', 'Hide water in cut area (model_volume_cutout.fx): Hides the ocean water in the area where the terrain has been cut out'],
        'cVtxAnimColorTex':["Color Map (model_vertex_anim.fx): See Houdini's documentation on its 'GameDev Vertex Animation Textures' ROP node"],
        'cVtxAnimNormalTex':["Normal Map (model_vertex_anim.fx): (Soft Only) See Houdini's documentation on its 'GameDev Vertex Animation Textures' ROP node"],
        'cVtxAnimNumFrames':["Number Of Frames (model_vertex_anim.fx): See Houdini's documentation on its 'GameDev Vertex Animation Textures' ROP node"],
        'cVtxAnimPaddedSizeX':["Padded Size X (model_vertex_anim.fx): See Houdini's documentation on its 'GameDev Vertex Animation Textures' ROP node"],
        'cVtxAnimPaddedSizeY':["Padded Size Y (model_vertex_anim.fx): See Houdini's documentation on its 'GameDev Vertex Animation Textures' ROP node"],
        'cVtxAnimPivMax':["Pivot Max (model_vertex_anim.fx): (Rigid Only) See Houdini's documentation on its 'GameDev Vertex Animation Textures' ROP node"],
        'cVtxAnimPivMin':["Pivot Min (model_vertex_anim.fx): (Rigid Only) See Houdini's documentation on its 'GameDev Vertex Animation Textures' ROP node"],
        'cVtxAnimPosMax':["Position Max (model_vertex_anim.fx): See Houdini's documentation on its 'GameDev Vertex Animation Textures' ROP node"],
        'cVtxAnimPosMin':["Position Min (model_vertex_anim.fx): See Houdini's documentation on its 'GameDev Vertex Animation Textures' ROP node"],
        'cVtxAnimPosTex':["Position Map (model_vertex_anim.fx): See Houdini's documentation on its 'GameDev Vertex Animation Textures' ROP node"],
        'cVtxAnimPosTex2':["Position Map 2 (model_vertex_anim.fx): See Houdini's documentation on its 'GameDev Vertex Animation Textures' ROP node"],
        'cVtxAnimRotTex':["Rotation Map (model_vertex_anim.fx): (Rigid Only) See Houdini's documentation on its 'GameDev Vertex Animation Textures' ROP node"],
        'cVtxAnimSpeed':["Speed (model_vertex_anim.fx): See Houdini's documentation on its 'GameDev Vertex Animation Textures' ROP node"],
        'cVtxAnimTexSizeX':["Active Pixels X (model_vertex_anim.fx): See Houdini's documentation on its 'GameDev Vertex Animation Textures' ROP node"],
        'cVtxAnimTexSizeY':["Active Pixels Y (model_vertex_anim.fx): See Houdini's documentation on its 'GameDev Vertex Animation Textures' ROP node"],
        'cWaterDepth':['Water Depth (model_water.fx): The perceived water depth through varying turbidity.'],
        'cWaterDepthFade':['Soft Depth Fade (model_water.fx): How much the water shall fade where it is near/intersecting with geometry to hide clipping artifacts.'],
        'cWaterDetailNormTex':['Water Detail Normal Map (model_water.fx): Normal map for the water detail texture'],
        'cWaterDetailTex':['Water Detail Map (model_water.fx): Water detail diffuse texture'],
        'cWaterDistortion':['Refract Distortion Strength (model_water.fx): How much should the water refraction be distorted (refraction strength).'],
        'cWaterFlowTex':["Water Flow Map (model_water.fx): Water flow texture. Red and green channels specify the flow speed in U and V direction. Similar to normal maps, a value of 128 specifies zero speed. Values less than 128 moves in negative direction, values greater than 128 in positive direction. The blue channel controls the normal map's intensity. The alpha channel serves as refraction mask and also controls the distortion (black = no distortion)."],
        'cWaterFoam':['Foam (model_water.fx): How much foam is applied depending on the water depth.'],
        'cWaterTexScale':['Water Tex Scale (model_water.fx): Water texture scaling for normal (only with flow map), foam and detail map.'],
        'cWaveAngle':['Angle (model_planet_water.fx): Angle of the waves'],
        'cWaveHeightA':["Height A (model_planet_water.fx): First wave's height"],
        'cWaveHeightB':["Height B (model_planet_water.fx): Second wave's height"],
        'cWaveHeightC':["Height C (model_planet_water.fx): Third wave's height"],
        'cWaveNoiseTex':['Wave Texture File (model_planet_water.fx): Noise texture for waves'],
        'cWaveScaleA':["Scale A (model_planet_water.fx): First wave's size"],
        'cWaveScaleB':["Scale B (model_planet_water.fx): Second wave's size"],
        'cWaveScaleC':["Scale C (model_planet_water.fx): Third wave's size"],
        'cWaveSpeed':['Speed (model_planet_water.fx): Wave wind speed'],
        'cWaveStretch':['Stretching (model_planet_water.fx): Width/length ratio of the waves'],
        'cWaveTotalHeight':['Total Height (model_planet_water.fx): Total wave height'],
        'cWaveTotalScale':['Total Scale (model_planet_water.fx): Size of the waves'],
        'cWindColorBoost':['Wind Color Boost (prop_plant.fx): Controls how strongly farm field wind affects color', 'Wind Color Boost (prop_terrain_object.fxh): Controls how strongly farm field wind affects color'],
        'cWindRippleMeshIntensity':["Wind Ripple Mesh Intensity (model_materials.fxh): Controls the wind ripples' intensity on the mesh vertices"],
        'cWindRippleNormalIntensity':["Wind Ripple Normal Intensity (model_materials.fxh): Controls the wind ripples' normal-mapped intensity"],
        'cWindRippleSpeed':["Wind Ripple Speed (model_materials.fxh): Controls the wind ripple texture's movement speed"],
        'cWindRippleTex':['Wind Ripple Texture (model_materials.fxh): The texture used for the wind ripple effect'],
        'cWindRippleTiling':["Wind Ripple Tiling (model_materials.fxh): Controls the wind ripple texture's tiling size"],
        'cZenithColor':['Zenith Color (model_planet_water.fx): Atmosphere color at zenith (for sky reflection)'],
        'DETAIL_MAP_ENABLED':["Detail Map (model_water.fx): Enables the detail texture: An opaque texture that's put on-top of the water surface. The water surface is visible in areas where this texture's alpha channel is non-white. If flow map is active, this one is distorted too."],
        'DIFFUSE_ENABLED':['Diffuse + Alpha (cloth.fx): Enables the diffuse texture', 'Diffuse + Alpha (model_frame_cycle.fx): Enables Diffuse Texture', 'Diffuse Texture (model_planet_water.fx): Enables the diffuse texture', 'Diffuse + Alpha (model_video.fx): Enables Diffuse Texture', 'Diffuse + Alpha (prop_plant.fx): Enables Diffuse Texture', 'Diffuse + Alpha (model_materials.fxh): Enables Diffuse Texture'],
        'DISABLE_PLANT_GLOSSINESS':['Disable Glossiness (prop_plant.fx): (PERFORMANCE OPTIMIZATION) Disable all reflection/specular lighting'],
        'DISPLACEMENT_ENABLED':["Displacement Enable (prop_decal_detail.fx): Must match value 'Height Map Enable' in decal material."],
        'DOUBLE_SIDED':['Double-Sided (model_vertex_anim.fx): Renders both sides of the model, effectively disabling back-face culling. This is useful for cloth.', "Double-Sided (prop_plant.fx): Render every triangle's front and back face.", "Double-Sided (prop_terrain_object.fxh): Render every triangle's front and back face."],
        'DYE_MASK_ENABLED':['Dye Mask (cloth.fx): Enables the dye mask texture', 'Dye Mask (model_materials.fxh): Enables the dye mask texture'],
        'ENABLE_ARCTIC_SHADING':['Enable Arctic Settings (prop_terrain.fx): Enables material options for props placed on arctic terrain'],
        'ENABLE_TERRAIN_MATERIAL':["Terrain Material (prop_terrain.fx): Maps a terrain texture on this object, similar to terrain's own material mapping"],
        'FADE_OUT_SHADOW':["Fade out shadows (prop_plant.fx): Fade out shadows casted by this object when it's far away"],
        'FARM_FIELD_WIND':['Farm Field Wind (prop_plant.fx): Enables Farm Field Wind', 'Farm Field Wind (prop_terrain_object.fxh): Enables Farm Field Wind'],
        'Flags':['Flags (Prop): A flag of 0 is equal to not adapting to the terrain height. If one, the prop will adapt to the terrain height.'],
        'FLOW_MAP_ENABLED':["Flow Map (model_water.fx): Enables the flow texture: Applies a flow-like moving distortion effect on the foam and (if active) the detail map and (if the ocean wave tex doesn't override it) the normal map."],
        'FOAM_ENABLED':['Foam Texture (model_planet_water.fx): Enables the foam texture'],
        'FORCE_ALPHA_BLEND':['Force Alpha Blend (prop_impostor.fx): Force alpha blending instead of alpha testing', 'Force Alpha Blend (prop_simple_pbr.fx): Force alpha blending instead of alpha testing'],
        'FRAME_BLEND_MODE':['Blend Mode (model_frame_cycle.fx): Choose a blend mode (0 = scale-in, 1 = roll-in left to right, 2 = roll-in from top-left corner, 3 = simple)'],
        'GLOW_ENABLED':['Glow (model_materials.fxh): Enables Glow'],
        'HEIGHT_MAP_ENABLED':['Height (decal_terrain.fx): Enables bump mapping via height map', 'Height Map (model_materials.fxh): Enables surface details via height map.'],
        'ICE_SNOW_ENABLED':['Ice/Snow (decal_terrain.fx): Enables icyness/snowness baking.'],
        'INVERSE_LOGO_COLORING':["Inverse Logo Coloring (cloth.fx): Inverts the atlas logo coloring: The logo's color stays as it is and the surrounding non-logo area is dye-colored."],
        'LOGO_ATLAS_ENABLED':['Logo Atlas (cloth.fx): Enables texture atlas support. Note: The mesh needs a second set of UV coordinates!'],
        'MANUAL_SUN_SPEC_ENABLED':['Manual sun specular (model_planet_water.fx): Enables manual tweaking of the sun specular parameters'],
        'METALLIC_TEX_ENABLED':['Metallic (functions_pbr.fxh): Enables the metallic texture'],
        'NIGHT_GLOW_ENABLED':['Night Glow Map (model_materials.fxh): Enables an additional glow map that is only applied during night.'],
        'NORMAL_ENABLED':['Normal + Gloss (cloth.fx): Enables the normal texture', 'Normal + Gloss (decal_terrain.fx): Enables normal mapping', 'Normal + Glow + Gloss (model_materials.fxh): Enables Normal Mapping'],
        'NORMAL_MAP_ENABLED':['Normal Map Enable (prop_decal_detail.fx): Enables Normal Mapping', 'Normal Map Enable (prop_plant.fx): Enables Normal Mapping', 'Normal Map Enable (prop_terrain_object.fxh): Enables Normal Mapping'],
        'NumBonesPerVertex':["Number of bones per vertex, has to be zero for non animated models."],
        'PARALLAX_ENABLED':["Parallax Rendering (model_planet.fx): Enables special 'parallax-' instead of 'world-position-' rendering"],
        'PARALLAX_MAPPING_ENABLED':['Parallax Mapping (model_materials.fxh): Enables parallax mapping (needs a height map texture).'],
        'PLANET_ENABLED':['Planet Enabled (model_planet.fx): Enables the planet rendering (no clouds without planet)'],
        'PLANET_WATER_NORMAL_ENABLED':['Normal+Gloss Texture (model_planet_water.fx): Enables the normal/gloss texture'],
        'PROP_TINT_ENABLED':['Prop Tinting (prop_plant.fx): Enables prop tinting (Separate from terrain tinting)'],
        'RIPPLES_ENABLED':['Ripples (cloth.fx): Enables the wind ripples texture. This is an additional shader-only cloth effect that mimics small cloth ripples moved by the wind.'],
        'SELF_SHADOWING_ENABLED':['Self Shadowing (model_materials.fxh): Enables self shadowing (needs a height map texture).'],
        'SEPARATE_AO_TEXTURE':['Separate AO (functions_pbr.fxh): Uses a separate ambient occlusion texture. Metallicity texture must be enabled. NOTE: The mesh needs a second UV channel!'],
        'ShaderID':["Shader ID: Determines which shader is used. 8 for normal models, 1 for decals, 0 for cloth, 5 for cutout."],
        'SNOW_ENABLED':['Snow Enabled (functions_snow.fxh): Enables the snow'],
        'SNOW_MASK_ENABLED':['Snow Mask (functions_snow.fxh): Enables the snow mask texture'],
        'TEXTURE_ATLAS_ENABLED':['Texture Atlas (model_decal.fx): Enables texture atlas support'],
        'USE_DISPLACEMENT_MAPPING':['Use Displacement Mapping (model_materials.fxh): Enables displacement mapping for surface details (Parallax mapping is used otherwise).'],
        'USE_SMALL_WAVE_TEXTURE':["Use Ocean Wave Texture (model_water.fx): Uses the engine-internal animated small-wave textures that's also used for ocean, lake and river rendering.  !!! NOTE: To see this in BobNet, you need an active ocean water !!!"],
        'USE_TERRAIN_TINT':["Use Terrain Tint (prop_terrain.fx): Applies terrain's tint texture onto this prop"],
        'VariationEnabled':["Variation Enabled: If one, the game will choose one of the props from this container randomly."],
        'VERTEX_COLOR_FOAM':['VertexColor Foam (model_water.fx): Enables foam distribution via vertex colors (red color controls foam: black = 0 = no foam, red = 1 = full foam)'],
        'VERTEX_COLORED_TERRAIN_ADAPTION':["Vertex color controls terrain adaption (model_cutout.fx): Vertex color (red channel) controls the terrain height adaption. Note: Needs 'Adjust to terrain height' to be enabled.", "Vertex color controls terrain adaption (model_materials.fxh): Vertex color (red channel) controls the terrain height adaption. Note: Needs 'Adjust to terrain height' to be enabled."],
        'VertexFormat':["Vertex Format: Vertex Format of the model, has to match the exported vertex format. Valid values are (among others) P4h_N4b_G4b_B4b_T2h (normal model), P4h_N4b_G4b_B4b_T2h_I4b (animated model), P4h_N4b_G4b_B4b_T2h_I4b_W4b, P3f_N3f_G3f_T2f_T1f_T1f_T1f(decal), P3f_N3b,T2f (sail cloth), P4h (cutout)"],
        'VTX_ANIM_DOUBLE_TEX':["Double Texture (Higher Precision) (model_vertex_anim.fx): See Houdini's documentation on its 'GameDev Vertex Animation Textures' ROP node"],
        'VTX_ANIM_LOOPED':['Looped (model_vertex_anim.fx): Runs the animation infinitely looped. Note that disabling this option is really only useful for sequence-controlled animations!'],
        'VTX_ANIM_PACK_NORM':["Pack Normal (model_vertex_anim.fx): See Houdini's documentation on its 'GameDev Vertex Animation Textures' ROP node"],
        'VTX_ANIM_PAD_POW_2':["Padded to Power of 2 Texture Sizes (model_vertex_anim.fx): See Houdini's documentation on its 'GameDev Vertex Animation Textures' ROP node"],
        'VTX_ANIM_SEQUENCE_CONTROLLED':["Sequence Controlled (model_vertex_anim.fx): Aligns the animation's timing to running sequences, otherwise to the global timer. Use this if you want to control this vtx animation via a sequence."],
        'VTX_ANIMATION_TEXTURES_ENABLED':['Enable Vertex Animation Textures (model_vertex_anim.fx): Enables vertex animation textures exported from Houdini'],
        'VTX_ANIMATION_TEXTURES_TYPE':['Type (model_vertex_anim.fx): 0 = Soft (cloth), 1 = Rigid (debries), 2 = Fluid'],
        'WATER_CUTOUT_ENABLED':["Water Cut-out (model_materials.fxh): If enabled: This mesh can't be covered by ocean water"],
        'WAVE_NOISE_TEX_ENABLED':['Wave Texture (model_planet_water.fx): Enables the wave noise texture'],
        'WAVE_TEXTURE_USES_2ND_UVS':["Use 2nd UVs (model_planet_water.fx): Use the model's second UV channel for the waves' texture coordinates"],
        'WIND_RIPPLES_ENABLED':['Wind Ripples (model_materials.fxh): Enables wind ripples for a cloth-like ripple shading effect'],
}
def help_for_key(key):
    return '\n'.join(info_by_key.get(key, ["UNKNOWN"]))